version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn
      - run:
          name: Run Prettier
          command: |
            npx prettier --check .
      - run:
          name: Build
          command: |
            make sdist
      - store_artifacts:
          path: ./cycle-ink-driver-*.tgz

workflows:
  version: 2
  build:
    jobs:
      - build
